### ISSUE TITLE
Error with combatlogx

### ISSUE THREAD

**Issue by justmangoou** [gronnmann/CoinFlipper#13]
LOG:
https://pastebin.com/mVLabKr9fbclid=IwAR2aPPCFQPQH2d1u5Xs5KKgHRoESNtMMiTCFvN0TsRqSwcRosEZVnKoUl2k

Version:
CoinFlipper: 2.4_3
CombatLogX: 9.9.2.1

**Comment by gronnmann** [comment]
Is this still present on the newest version?

**Comment by justmangoou** [comment]
Well it's working good now but I haven't deep-test yet

**Comment by gronnmann** [comment]
Seems like many CombatLogX versions have different API.
Have updated CoinFlipper 2.8 to support the latest one.
