### ISSUE TITLE
Could not pass event InventoryClickEvent to CoinFlipper v2.7

### ISSUE THREAD

**Issue by andrewkm** [gronnmann/CoinFlipper#19]
https://pastebin.com/raw/CpBKxeTZ

Running CoinFlipper 2.7
Running Paper 1.16.4 Build 294.

PS: How does one go about building this plugin?
Not your standard setup it seems, no pom.xml and all.

**Comment by gronnmann** [comment]
Hi!
Seems like it has been fixed, I just haven't compiled the newerst version. Will do it in an hour or two.
The plugin was made long before I knew maven, so building it is just downloading all sources, dependencies, then compiling. Will see if I can make it work with maven soon.

**Comment by andrewkm** [comment]
Thanks, working with maven would be great! <3
Would allow us to build development versions with ease via Jenkins.

**Comment by gronnmann** [comment]
Works with maven now :)
