### ISSUE TITLE
If game is in progress and server shuts down both users lose money.

### ISSUE THREAD

**Issue by andrewkm** [gronnmann/CoinFlipper#20]
If game is in progress and server shuts down both users lose money.
Instead, the shutdown process of CoinFlipper should allow all current games to finish before disabling plugin.

**Comment by gronnmann** [comment]
Hi!
I have now made the money received the moment the player challenges the bet - so noone will lose money when bets are played.
Thank you for the heads up
Please download 2.80 when it comes up and you should be good
